"use client";
import { discountLabel } from "@/lib/pricing";

import { Ban, Printer, RotateCcw } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { SaleReceipt } from "@/components/pos/Receipt";
import { useConfirm } from "@/components/ui/ConfirmProvider";
import styles from "@/app/pos/sales/[id]/detail.module.css";

type Sale = { id: string; sale_no: string; status: string; subtotal: string; discount_type: string; discount_value: string; discount: string; total: string; amount_received: string; change_given: string; payment_method: string; created_at: string; cancellation_reason: string | null; branch: { name: string; address: string | null; phone: string | null }; cashier: { name: string }; cancelled_by_staff: { name: string } | null; items: Array<{ id: string; product_name: string; quantity: string; unit_price: string; line_total: string }>; transaction: { receipt: { receipt_no: string } | null } | null };
const money = new Intl.NumberFormat("en-LK", { style: "currency", currency: "LKR" });

export function SaleDetail({ saleId }: { saleId: string }) {
  const confirm = useConfirm();
  const [sale, setSale] = useState<Sale | null>(null); const [viewerRole, setViewerRole] = useState(""); const [canCancel, setCanCancel] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/pos/sales/${saleId}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Sale could not be loaded"); setSale(data.sale); setViewerRole(data.viewer_role ?? ""); setCanCancel(data.can_cancel); } catch (reason) { setError(reason instanceof Error ? reason.message : "Sale could not be loaded"); } finally { setLoading(false); } }, [saleId]);
  useEffect(() => { void load(); }, [load]);
  async function print() { window.print(); if (sale) void fetch(`/api/pos/sales/${sale.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "mark_printed" }) }); }
  async function cancel() { if (!sale || busy) return; const reason = await confirm({ title: "Cancel this sale?", description: "All items will be returned to stock. Enter a reason for the cancellation.", inputLabel: "Cancellation reason", confirmLabel: "Cancel sale", danger: true }); if (!reason) return; setBusy(true); setError(""); const response = await fetch(`/api/pos/sales/${sale.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "cancel", reason }) }); const data = await response.json(); if (response.ok) await load(); else setError(data.error ?? "Sale could not be cancelled"); setBusy(false); }
  if (loading) return <main className={styles.page}><p className={styles.state}>Loading sale…</p></main>;
  if (!sale) return <main className={styles.page}><p className={styles.error}>{error || "Sale not found"}</p></main>;
  const receiptNo = sale.transaction?.receipt?.receipt_no ?? "Receipt pending";
  return <main className={styles.page}><div className={styles.shell}><nav className={styles.back}><Link href="/pos/sales">← Sales</Link><Link href="/pos/sales/new"><RotateCcw size={17}/>New sale</Link></nav><header className={styles.title}><div><p>SALE RECORD</p><h1>{sale.sale_no}</h1><span>{new Date(sale.created_at).toLocaleString("en-GB")} · {sale.branch.name}</span></div><span className={sale.status === "CANCELLED" ? styles.cancelled : styles.complete}>{sale.status}</span></header>{error && <p className={styles.error} role="alert">{error}</p>}<div className={styles.grid}><section className={styles.card}><h2>Items</h2><div className={styles.items}>{sale.items.map(item => <div key={item.id}><span><strong>{item.product_name}</strong><small>{Number(item.quantity)} × {money.format(Number(item.unit_price))}</small></span><b>{money.format(Number(item.line_total))}</b></div>)}</div></section><aside className={styles.card}><h2>Payment summary</h2><dl><div><dt>Receipt</dt><dd>{receiptNo}</dd></div><div><dt>Subtotal</dt><dd>{money.format(Number(sale.subtotal))}</dd></div><div><dt>{discountLabel(sale.discount_type, sale.discount_value)}</dt><dd>−{money.format(Number(sale.discount))}</dd></div><div className={styles.total}><dt>Total</dt><dd>{money.format(Number(sale.total))}</dd></div><div><dt>Received</dt><dd>{money.format(Number(sale.amount_received))}</dd></div><div><dt>Change</dt><dd>{money.format(Number(sale.change_given))}</dd></div><div><dt>Payment</dt><dd>{sale.payment_method}</dd></div>{viewerRole !== "CASHIER" && <div><dt>Cashier</dt><dd>{sale.cashier.name}</dd></div>}</dl>{sale.cancellation_reason && <p className={styles.reason}><strong>Cancellation:</strong> {sale.cancellation_reason}</p>}<div className={styles.actions}><button onClick={() => void print()}><Printer size={18}/>Print receipt</button>{canCancel && sale.status === "COMPLETED" && <button className={styles.danger} disabled={busy} onClick={() => void cancel()}><Ban size={18}/>{busy ? "Cancelling…" : "Cancel sale"}</button>}</div></aside></div></div><SaleReceipt receiptNo={receiptNo} saleNo={sale.sale_no} status={sale.status} branchName={sale.branch.name} branchAddress={sale.branch.address} branchPhone={sale.branch.phone} servedBy={sale.cashier.name} issuedAt={sale.created_at} items={sale.items} subtotal={sale.subtotal} discount={sale.discount} discountType={sale.discount_type} discountValue={sale.discount_value} total={sale.total} amountReceived={sale.amount_received} changeGiven={sale.change_given} paymentMethod={sale.payment_method}/></main>;
}
