import { BarChart3, BookOpenCheck, Boxes, Building2, PackageOpen, ReceiptText, ShoppingCart, Truck, UsersRound } from "lucide-react";
import Link from "next/link";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { Role } from "@prisma/client";
import { getCurrentStaff } from "@/lib/auth";
import styles from "./admin.module.css";

export default async function AdminPage() {
  const staff = await getCurrentStaff(new Request("http://localhost", { headers: headers() }));
  if (!staff) redirect("/login");
  if (staff.role !== Role.SUPER_ADMIN && staff.role !== Role.BRANCH_ADMIN) redirect("/pos/dashboard");
  const isSuperAdmin = staff.role === Role.SUPER_ADMIN;
  return <main className={styles.page}><div className={styles.shell}><header className={styles.header}><p>{isSuperAdmin ? "SUPER ADMIN" : "BRANCH ADMIN"}</p><h1>Overview</h1><span>{isSuperAdmin ? "Choose a top-level control area." : "Choose a branch operation area."}</span></header><section className={styles.cards}>{isSuperAdmin ? <><Link className={styles.card} href="/admin/branches"><Building2/><h2>Branches & reports</h2><p>Create branches and open each branch report from one clean table.</p><strong>Open →</strong></Link><Link className={styles.card} href="/admin/staff"><UsersRound/><h2>Staff & access</h2><p>Create and manage POS Super Admin, Branch Admin, and Cashier accounts.</p><strong>Open →</strong></Link><Link className={styles.card} href="/admin/suppliers"><Truck/><h2>Suppliers & accounts</h2><p>Review supplier records, purchases, balances, and payments by branch.</p><strong>Open →</strong></Link><Link className={styles.card} href="/admin/items"><PackageOpen/><h2>Items, services & packages</h2><p>View branch products, services, and package prices with branch and category filters.</p><strong>Open →</strong></Link><Link className={styles.card} href="/admin/expenses"><ReceiptText/><h2>Expenses</h2><p>Record branch expenses and maintain the expense name list.</p><strong>Open →</strong></Link></> : <><Link className={styles.card} href="/pos/bookings"><BookOpenCheck/><h2>Bookings</h2><p>Review online and walk-in bookings saved by the POS.</p><strong>Open →</strong></Link><Link className={styles.card} href="/pos/sales"><ShoppingCart/><h2>Sales</h2><p>Complete cafe sales, update stock, and print receipts.</p><strong>Open →</strong></Link><Link className={styles.card} href="/admin/suppliers"><Truck/><h2>Suppliers & accounts</h2><p>Manage supplier records, purchases, balances, and payments for your branch.</p><strong>Open →</strong></Link><Link className={styles.card} href="/admin/items"><PackageOpen/><h2>Items, services & packages</h2><p>Review product, service, and package price setup.</p><strong>Open →</strong></Link><Link className={styles.card} href="/admin/stock"><Boxes/><h2>Stock & wastage</h2><p>Manage branch stock quantities, wastage, and movement history.</p><strong>Open →</strong></Link><Link className={styles.card} href="/admin/expenses"><ReceiptText/><h2>Expenses</h2><p>Record branch expenses and maintain operating cost records.</p><strong>Open →</strong></Link><Link className={styles.card} href="/admin/reports"><BarChart3/><h2>Reports & analytics</h2><p>Track branch revenue, costs, wastage, and operating result.</p><strong>Open →</strong></Link></>}</section></div></main>;
}
